name: themoviebook
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

  gap: ^2.0.1
  phosphor_flutter: ^1.4.0
  smooth_page_indicator: ^1.0.1
  hooks_riverpod: ^2.3.0
  flutter_hooks: ^0.18.6
  cloud_firestore: ^4.4.4
  firebase_dynamic_links: ^5.0.16
  flutter_local_notifications: ^13.0.0
  image_picker: ^0.8.6+4
  google_sign_in: ^6.0.2
  sign_in_with_apple: ^4.3.0
  firebase_auth: ^4.2.2
  intl: ^0.18.0
  firebase_messaging: ^14.2.6
  firebase_crashlytics: ^3.0.16
  dio: ^5.0.1
  flutter_svg: ^2.0.2
  google_fonts: ^4.0.3
  share: ^2.0.4
  path_provider: ^2.0.13
  equatable: ^2.0.5
  collection: ^1.17.0
  sqflite: ^2.2.5
  video_player: ^2.5.3
  video_thumbnail: ^0.5.3
  lottie: ^2.2.0
  share_plus: ^6.3.1
  flex_color_scheme: ^6.1.2
  image: ^4.0.15
  go_router: ^6.2.0
  logger: ^1.2.2
  flutter_screenutil: ^5.6.1
  firebase_core: ^2.7.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  uuid: ^3.0.7
  riverpod_generator: ^2.0.0
  riverpod_annotation: ^2.0.0
  flutter_lints: ^2.0.0
  very_good_analysis: ^4.0.0+1
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  mockito: ^5.3.2

flutter:

  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/onboarding/
